## Vehicle Maintenance Telemetry

This dataset was downloaded from Kaggle https://www.kaggle.com/datasets/tejalaveti2306/vehicle-maintenance-telemetry-data?resource=download

This dataset contains synthetically generated vehicle telemetry readings designed for developing and evaluating predictive maintenance models. It simulates sensor data, operational parameters, and eventual failure events for a fleet of vehicles over time.

Context / Background:
Predictive maintenance is crucial in fleet management to anticipate and prevent costly vehicle failures. This dataset aims to provide a realistic, yet controlled, environment to develop machine learning models that can predict impending issues (e.g., engine, brake, battery failures) based on time-series telemetry data.

Content:
The dataset is structured with one row per telemetry reading per vehicle at a given timestamp. Please refer to Kaggle Data Card for more details regarding key features.

Data Generation:
This dataset was generated synthetically to mimic real-world vehicle telemetry patterns. Key parameters were designed to show realistic operational fluctuations, and some parameters were programmed to degrade gradually over time, culminating in simulated 'failure' events (Engine, Brake, Battery) for a subset of vehicles. This degradation allows for the development of models that can identify pre-failure conditions.

Acknowledgements:
This dataset was synthetically generated as part of a project to demonstrate predictive maintenance capabilities.

### Import Python libraries and read files

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn as sk

In [3]:
telemetry = pd.read_csv('../data/raw/synthetic_telemetry_data.csv')

In [4]:
telemetry.head()

,vehicle_id,brand,timestamp,odometer_reading,engine_temp_c,engine_rpm,oil_pressure_psi,coolant_temp_c,fuel_level_percent,fuel_consumption_lph,...,vehicle_speed_kph,ambient_temp_c,humidity_percent,gps_latitude,gps_longitude,engine_failure_imminent,brake_issue_imminent,battery_issue_imminent,failure_date,failure_type
0,VEH0000,BMW,2023-01-01 00:00:00,31381.561743,99.388213,2212.155243,55.522505,91.788105,68.368162,4.076315,...,116.501239,24.187057,83.785796,31.986296,78.203395,0,0,0,2050-01-01 00:00:00,No Failure
1,VEH0000,BMW,2023-01-01 00:56:00,31391.284155,84.118706,961.795251,57.799346,87.283282,99.064394,7.059168,...,39.409933,15.148875,57.418501,30.620539,84.389727,0,0,0,2050-01-01 00:00:00,No Failure
2,VEH0000,BMW,2023-01-01 01:28:00,31428.088015,103.521431,742.050437,50.398848,83.503155,80.280244,10.792362,...,82.077798,23.138714,80.540135,30.634997,79.039234,0,0,0,2050-01-01 00:00:00,No Failure
3,VEH0000,BMW,2023-01-01 01:27:00,31463.271669,91.130527,2723.042461,41.719715,90.997963,13.892586,1.564630,...,70.294428,35.058947,57.221563,33.490971,76.107248,0,0,0,2050-01-01 00:00:00,No Failure
4,VEH0000,BMW,2023-01-01 01:00:00,31490.411858,96.887263,2647.979969,38.438964,93.029011,20.871931,6.814662,...,74.028392,18.024207,47.680115,28.392300,83.160007,0,0,0,2050-01-01 00:00:00,No Failure

In [5]:
print(telemetry.dtypes)

vehicle_id                  object
brand                       object
timestamp                   object
odometer_reading           float64
engine_temp_c              float64
engine_rpm                 float64
oil_pressure_psi           float64
coolant_temp_c             float64
fuel_level_percent         float64
fuel_consumption_lph       float64
engine_load_percent        float64
throttle_pos_percent       float64
air_flow_rate_gps          float64
exhaust_gas_temp_c         float64
vibration_level            float64
engine_hours               float64
brake_fluid_level_psi      float64
brake_pad_wear_mm          float64
brake_temp_c               float64
abs_fault_indicator          int64
brake_pedal_pos_percent    float64
wheel_speed_fl_kph         float64
wheel_speed_fr_kph         float64
wheel_speed_rl_kph         float64
wheel_speed_rr_kph         float64
battery_voltage_v          float64
battery_current_a          float64
battery_temp_c             float64
alternator_output_v        float64
battery_charge_percent     float64
battery_health_percent     float64
vehicle_speed_kph          float64
ambient_temp_c             float64
humidity_percent           float64
gps_latitude               float64
gps_longitude              float64
engine_failure_imminent      int64
brake_issue_imminent         int64
battery_issue_imminent       int64
failure_date                object
failure_type                object
dtype: object

In [6]:
telemetry.describe()

,odometer_reading,engine_temp_c,engine_rpm,oil_pressure_psi,coolant_temp_c,fuel_level_percent,fuel_consumption_lph,engine_load_percent,throttle_pos_percent,air_flow_rate_gps,...,battery_charge_percent,battery_health_percent,vehicle_speed_kph,ambient_temp_c,humidity_percent,gps_latitude,gps_longitude,engine_failure_imminent,brake_issue_imminent,battery_issue_imminent
count,1970.000000,1970.000000,1970.000000,1970.000000,1970.000000,1970.000000,1970.000000,1970.000000,1970.000000,1970.000000,...,1970.000000,1970.000000,1970.000000,1970.000000,1970.000000,1970.000000,1970.000000,1970.000000,1970.000000,1970.000000
mean,55805.596064,95.098185,2011.461245,44.705878,89.874554,47.998493,5.123180,39.999500,29.981324,50.292807,...,70.092167,94.329009,70.201288,29.966583,59.783230,31.492223,80.016424,0.003553,0.008122,0.006091
std,25276.174846,5.201481,760.883948,10.115871,2.985144,29.182622,2.919474,19.273029,18.799032,19.670713,...,17.161083,2.541468,38.185877,9.867784,14.721301,1.988963,2.937999,0.059519,0.089777,0.077829
min,13578.948264,77.781925,700.000000,5.928049,78.797191,0.166009,0.000000,0.000000,0.000000,0.000000,...,40.018290,90.162163,0.000000,-17.116179,9.914752,28.000396,75.002955,0.000000,0.000000,0.000000
25%,34537.434560,91.593183,1457.167122,37.687975,87.853215,22.081471,2.990431,26.540634,16.268606,36.972980,...,55.096188,91.960024,42.645593,23.609246,50.103555,29.787474,77.373052,0.000000,0.000000,0.000000
50%,56545.906171,95.084360,1998.276722,45.024308,89.767156,47.287384,5.052483,39.383741,28.781407,50.179637,...,70.652447,94.172950,69.336619,30.271354,59.574084,31.509410,80.009871,0.000000,0.000000,0.000000
75%,77938.260730,98.620236,2535.801415,51.481993,91.926039,73.024963,7.132336,53.384306,42.784640,64.408787,...,84.273524,96.249211,96.188556,36.709522,69.550834,33.181098,82.629875,0.000000,0.000000,0.000000
max,100409.771733,119.322471,4167.823670,80.267052,100.659740,99.997479,15.127696,100.000000,91.815640,106.856022,...,99.968430,99.386264,180.000000,63.348462,117.766913,34.997221,84.997696,1.000000,1.000000,1.000000